"""add risk findings and approval requirements

Revision ID: 1e3201177cb4
Revises: f63b319b149b
Create Date: 2026-08-21 13:43:35.875309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3201177cb4'
down_revision: Union[str, Sequence[str], None] = 'f63b319b149b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engineering_change_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SAFETY_BOARD', 'CONTROLS_ENGINEER', 'PLANT_MANAGER', 'COMPLIANCE_ENGINEER', name='approvalrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engineering_change_id'], ['engineering_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requirements_engineering_change_id'), 'approval_requirements', ['engineering_change_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engineering_change_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('SAFETY', 'CONTROLS', 'PRODUCTION', 'COMPLIANCE', name='riskcategory'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='riskseverity'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engineering_change_id'], ['engineering_changes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['context_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_engineering_change_id'), 'risk_findings', ['engineering_change_id'], unique=False)
    op.create_index(op.f('ix_risk_findings_node_id'), 'risk_findings', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_findings_node_id'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_engineering_change_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_approval_requirements_engineering_change_id'), table_name='approval_requirements')
    op.drop_table('approval_requirements')
    # ### end Alembic commands ###
