"""add engineering context graph

Revision ID: 6db8802940bf
Revises: bd5aaca6aaa9
Create Date: 2026-08-21 12:06:18.174357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db8802940bf'
down_revision: Union[str, Sequence[str], None] = 'bd5aaca6aaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'ASSET', 'COMPONENT', 'MATERIAL', 'DOCUMENT', 'PROCESS', name='contextnodetype'), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_nodes_metadata', 'context_nodes', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_context_nodes_site_id'), 'context_nodes', ['site_id'], unique=False)
    op.create_index('uq_context_nodes_type_identifier', 'context_nodes', ['type', 'identifier'], unique=True)
    op.create_table('context_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PART_OF', 'CONTROLS', 'SENSES', 'POWERED_BY', 'DESCRIBES', 'GOVERNS', name='contextrelationshiptype'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['context_nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['context_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', 'relationship_type', name='uq_context_edge_relationship')
    )
    op.create_index('ix_context_edges_child_id', 'context_edges', ['child_id'], unique=False)
    op.create_index('ix_context_edges_parent_id', 'context_edges', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_edges_parent_id', table_name='context_edges')
    op.drop_index('ix_context_edges_child_id', table_name='context_edges')
    op.drop_table('context_edges')
    op.drop_index('uq_context_nodes_type_identifier', table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_site_id'), table_name='context_nodes')
    op.drop_index('ix_context_nodes_metadata', table_name='context_nodes', postgresql_using='gin')
    op.drop_table('context_nodes')
    # ### end Alembic commands ###
