"""feat: add event id to engineering context reports

Revision ID: b35c7f6cb602
Revises: cbd68def464b
Create Date: 2026-08-21 21:43:50.300843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35c7f6cb602'
down_revision: Union[str, Sequence[str], None] = 'cbd68def464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "engineering_context_reports",
        sa.Column("event_id", sa.UUID(), nullable=True),
    )

    op.execute(
        """
        UPDATE engineering_context_reports
        SET event_id = gen_random_uuid()
        WHERE event_id IS NULL
        """
    )

    op.alter_column(
        "engineering_context_reports",
        "event_id",
        nullable=False,
    )

    op.create_index(
        op.f("ix_engineering_context_reports_event_id"),
        "engineering_context_reports",
        ["event_id"],
        unique=True,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_context_reports_event_id'), table_name='engineering_context_reports')
    op.drop_column('engineering_context_reports', 'event_id')
    # ### end Alembic commands ###
