"""feat: add engineering_context_reports table

Revision ID: cbd68def464b
Revises: 1e3201177cb4
Create Date: 2026-08-21 20:35:29.773611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd68def464b'
down_revision: Union[str, Sequence[str], None] = '1e3201177cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_context_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engineering_change_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engineering_change_id'], ['engineering_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_context_reports_engineering_change_id'), 'engineering_context_reports', ['engineering_change_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_context_reports_engineering_change_id'), table_name='engineering_context_reports')
    op.drop_table('engineering_context_reports')
    # ### end Alembic commands ###
