"""add change actions

Revision ID: f63b319b149b
Revises: 6db8802940bf
Create Date: 2026-08-21 12:47:08.054210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f63b319b149b'
down_revision: Union[str, Sequence[str], None] = '6db8802940bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engineering_change_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'MODIFY', 'REMOVE', 'REPLACE', name='changeactiontype'), nullable=False),
    sa.Column('proposed_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engineering_change_id'], ['engineering_changes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['context_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_actions_engineering_change_id'), 'change_actions', ['engineering_change_id'], unique=False)
    op.create_index(op.f('ix_change_actions_node_id'), 'change_actions', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_actions_node_id'), table_name='change_actions')
    op.drop_index(op.f('ix_change_actions_engineering_change_id'), table_name='change_actions')
    op.drop_table('change_actions')
    # ### end Alembic commands ###
